# Generated by Django 5.2.7 on 2025-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("moderator", "Модератор"),
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                help_text="Выберите роль пользователя",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
