# Generated by Django 5.2.7 on 2025-10-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
