# Generated by Django 5.2.7 on 2025-10-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название курса', max_length=255, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='edumanage/courses', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название урока', max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='edumanage/lessons', verbose_name='Превью')),
                ('video_url', models.URLField(blank=True, help_text='Добавьте ссылку', null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edumanage.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
