# Generated by Django 5.2.7 on 2025-10-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edumanage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                default="admin@example.com",
                help_text="Кто создал курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                default="admin@example.com",
                help_text="Кто создал урок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда была создана подписка",
                        verbose_name="Дата подписки",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс, на который оформлена подписка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="edumanage.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, подписанный на курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "indexes": [
                    models.Index(
                        fields=["user"], name="edumanage_s_user_id_bb8209_idx"
                    ),
                    models.Index(
                        fields=["course"], name="edumanage_s_course__29077a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="edumanage_s_created_69e53c_idx"
                    ),
                ],
                "unique_together": {("user", "course")},
            },
        ),
    ]
